### ISSUE TITLE
Overlap issues for wordclouds

### ISSUE THREAD

**Issue by cschwem2er** [GuangchuangYu/ggplotify#1]
Hi,

first of all thank you for the awesome package, the possibility to convert base plots to ggplots is super useful! There is one specific use case though (very common for text analysis) where it does not seem to work quite well: plotting word clouds.

```
library(wordcloud)
library(ggplotify)
library(ggplot2)

wordcloud(c(letters, LETTERS, 0:9), seq(1, 1000, len = 62))
```
![image](https://user-images.githubusercontent.com/7460499/39405544-1dd0d406-4ba7-11e8-978b-fc3751a6cef5.png)

```
as.ggplot(~wordcloud(c(letters, LETTERS, 0:9), seq(1, 1000, len = 62)))
```
![image](https://user-images.githubusercontent.com/7460499/39405547-32f3bf9c-4ba7-11e8-83f5-8c2695471c8f.png)

Unfortunately, entities overlap each other here. Do you have any idea how to fix this?

**Comment by GuangchuangYu** [comment]
enlarge the graphic device will fix this issue.
