### ISSUE TITLE
Doesn't play well with purrr::map()

### ISSUE THREAD

**Issue by pat-s** [GuangchuangYu/ggplotify#2]
Probably due to the required `~` character within `as.ggplot2()`. It probablys interfers with the `~` operator of `map()` and hence `map()` cannot find `.x` anymore. Leaving it out throws no error but then `as.ggplot2()` "fails to convert". 

```r
plots = map(speclibs, ~ as.ggplot(~ plot(.x)))

Fehler in plot(.x) : Objekt '.x' nicht gefunden
```

No reprex right now, sorry. But maybe you know where the clash is located. `speclibs` here is a list containing multiple objects that are correctly plotted by `plot()`.

If it helps, I can provide a reprex later. Thanks for the nice idea of this package!

**Comment by GuangchuangYu** [comment]
```r
d = list(a=1:10, b=1:10)
## function interface was documented in online vignette
plt = map(d, ~ as.ggplot(function() plot(.x)))
cowplot::plot_grid(plotlist=plt, ncol=2)
```

**Comment by pat-s** [comment]
Thanks! Didn't see it in the vignette.
