### ISSUE TITLE
Unable to convert base plots obtained from package flowFP

### ISSUE THREAD

**Issue by epgui** [GuangchuangYu/ggplotify#3]
Hello,

I am trying to convert [flowFP](https://bioconductor.org/packages/release/bioc/html/flowFP.html) base plots into grobs or ggplot objects, but am running into the following error:

```
Error in UseMethod("as.grob") : 
  no applicable method for 'as.grob' applied to an object of class "NULL"
```

I'm not even sure if this is a ggplotify issue _per se_ (and I apologize if it is not), but currently I am trying to fit multiple types of flowFP plots on a grid or layout in an rmarkdown/knitr document with PDF output, and I appear to have reached an impasse (the more obvious `layout()` and `par()` simply do not work with knitr apparently).

**Comment by GuangchuangYu** [comment]
reproducible example pls.
