### ISSUE TITLE
as.ggplot: unable to preserve titles and legends for plots from package eulerr

### ISSUE THREAD

**Issue by codetrainee** [GuangchuangYu/ggplotify#5]
I was trying to convert a venn diagram from `eulerr` package using `as.ggplot` but the title and legends are missing.

``` r
library(eulerr)
library(magrittr)
library(ggplotify)

df <- data.frame(A = c(1, 1, 0, 1, 0, 1),
                 B = c(0, 0, 1, 1, 1, 1),
                 C = c(1, 0, 1, 0, 1, 0))

p <- 
  df %>% 
  euler(.) %>%
  plot(.,
       main = "Test",
       quantities = TRUE,
       legend = list(side = "bottom")
  ) 

p 
```

![](https://i.imgur.com/TAuNiEN.png)

``` r
p %>% as.ggplot()
```

![](https://i.imgur.com/6aePhMc.png)

<sup>Created on 2019-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/62554273-6da1a180-b8a3-11e9-865d-9c4522e7fb11.png)

**Comment by GuangchuangYu** [comment]
version 0.0.4 that supports eulerr is now on cran.
